### ISSUE TITLE
OutgoingResponse.prototype.flush is deprecated

### ISSUE THREAD

**Issue by arboreal84** [expressjs/compression#100]
`OutgoingResponse.prototype.flush` is now deprecated. Prefer the new `flushHeaders` method.

See:
https://github.com/expressjs/compression/blob/master/index.js#L69
https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4

**Comment by dougwilson** [comment]
Can you provide the full code that reproduces that? We run tests on all versions of Node.js and none of them cause that message to be printed.

**Comment by arboreal84** [comment]
There will be no output.
The node project just marked that as deprecated in their documentation.

**Comment by dougwilson** [comment]
Yes, but that's you calling that method on Node.js core; it was deprecated because this module was already using it, i.e. it was deprecated so this module _could use it_ :)

**Comment by arboreal84** [comment]
I am not sure I understand.
This is deprecated for node 4, but on 6 and later I am not sure what the status is.

**Comment by dougwilson** [comment]
What is deprecated is calling the res.flush method provided by Node.js. This module never calls that method, instead it is installing a completely different method with the same name that is not deprecated. One of the reasons the Node.js method was deprecated is because they choose a name that conflicted with user land modules like this one, so the name was changed so we could continue to provide the res.flush method.

**Comment by arboreal84** [comment]
Ok, makes sense. Thanks for the clarification.
