### ISSUE TITLE
Feature Request: Support node-snappy

### ISSUE THREAD

**Issue by romulof** [expressjs/compression#105]
Add `node-snappy` as an optional dependency and create an option to enable it.

**Comment by dougwilson** [comment]
I wouldn't, because that module doesn't have a readme, was last published 2 years ago and the link to the repo is not founds on GitHub: https://www.npmjs.com/package/node-snappy

**Comment by romulof** [comment]
https://github.com/kesla/node-snappy

Last commit: Sep 16, 2016

**Comment by dougwilson** [comment]
Hi @romulof ah, it would be nice if they could update their npm module page I linked to above, then, for the `node-snappy` module. But even then, it seems they are not publishing the `node-snappy` module you're asking me to take a dependency on. Check out the publishing history of that module with the `npm` command line tool (and the npm web page):
```
$ npm info node-snappy time

{ modified: '2015-05-13T09:27:35.207Z',
  created: '2014-12-01T08:48:39.086Z',
  '0.0.1': '2014-12-01T08:48:39.086Z',
  '0.0.2': '2014-12-01T09:22:36.436Z',
  '0.0.3': '2014-12-01T09:28:54.485Z',
  '0.0.4': '2014-12-01T11:29:51.563Z',
  '0.0.6': '2014-12-02T09:22:52.998Z',
  '0.0.7': '2014-12-02T14:15:34.711Z',
  '0.0.8': '2014-12-03T07:24:14.776Z',
  '0.0.9': '2014-12-03T07:37:42.013Z',
  '0.0.10': '2014-12-03T07:38:26.151Z',
  '0.1.1': '2014-12-23T07:31:59.652Z',
  '0.1.2': '2014-12-23T07:38:26.978Z',
  '0.1.3': '2014-12-24T03:10:58.142Z',
  '0.1.4': '2015-05-13T09:27:35.207Z' }
```

Unstable version, no README on npm, almost 2 years since last publish, etc. doesn't make me want to take a dependency on `node-snappy` even if it's optional.

**Comment by blakeembrey** [comment]
@dougwilson It's `snappy` on NPM, but you'd probably want to check out the streaming version mentioned in the README. Would it make sense to make the available compressors plug-able by users submitting map of functions that return transform streams?

**Comment by romulof** [comment]
Sorry for the confusion. Too many snappys on NPM :P

As @blakeembrey have pointed, their npm package is `snappy`.
