### ISSUE TITLE
res.end() doesn't set the finished flag

### ISSUE THREAD

**Issue by jbatchelor-atlassian** [expressjs/compression#120]
The monkey-patch of `res.end()` doesn't set `res.finished = true`

The Node HTTP spec expects this to be done when `end` is called https://nodejs.org/api/http.html#http_response_finished

Cheers :)

**Comment by dougwilson** [comment]
The finished flag is automaticlly set once the response is actually finished when the underlying compressed response is finally sent. If you listen to the finished rvent on res, you'll get it emitted and then the finished flag will be set.

Unfortunately if our res.end set finished to true, then when we actually go to write out the last chunk, Node.js just ignores it since that flag is up.

If you know of a good solution, please let me know how to solve or even put together a pull request.

**Comment by jbatchelor-atlassian** [comment]
Ahhh I see, that's really unfortunate. Cheers the the event workaround. I imagine it's possible to make the `end()` work with finished but it's probably more effort than it's worth.

Thanks for the quick response. We'll just work around it :)
