### ISSUE TITLE
Doesn't seem to perform compression when running on Windows.

### ISSUE THREAD

**Issue by chriseaton** [expressjs/compression#148]
We have a really odd issue. We're using the standard configuration, and making requests to the server, everything looks correct even up to the point we flush the request, but for some reason, the output is not compressed and the headers are missing on Windows. 

Oddly, if we run the exact same code on Linux, the output is compressed.

We're not using a proxy or anything. 

Here's our output of getHeaders at the end of our response:
```
content-encoding:"gzip"
content-type:"application/json; charset=utf-8"
etag:"W/"1e928-ejrkE6/bCZuNbsnF8HFNVEAq/EU""
vary:"Accept-Encoding"
```

Here's what the browser is showing (and no, the size is not showing the compressed size):
![image](https://user-images.githubusercontent.com/5247568/47057845-501a1480-d177-11e8-8392-60e354838c1e.png)

You can see the eTag is the same.    
No idea what's going on here - any help would be appreciated.

**Comment by chriseaton** [comment]
Hmm... so what's strange is I just ran your demo app - and it didn't compress for me:
I'm on Windows 10 Pro.
Trying on Chrome and Edge, both produce non-compressed responses... very wacky:

### Chrome
![image](https://user-images.githubusercontent.com/5247568/47058467-03840880-d17a-11e8-9d8a-27c7e9bbd54d.png)

### Edge
![image](https://user-images.githubusercontent.com/5247568/47058491-21ea0400-d17a-11e8-8717-eda9bca1e476.png)

This is the weirdest thing I've seen - because it even seems to leave the app with all the proper headers. What's odd is I also deployed this to a Windows 2012 R2 Server and had the same responses.

**Comment by dougwilson** [comment]
Are you sure you don't have some sort of WAF installed on the machine that is silently uncompressing responses? Perhaps, does this happen for requests over HTTPS vs over HTTP? If it only happens on HTTP, it would seem to point to somethig on your machine is hijacking your traffic at some point, since a HTTPS request is encrypted to the web browser.

I've seen a few people report no compressing here and it turned out to be an anti virus or other scanning software that embeds into your network stack.

**Comment by chriseaton** [comment]
That's an interesting thought - I just tried FF on Windows Server 2012 R2, and no dice either:

![image](https://user-images.githubusercontent.com/5247568/47058780-590ce500-d17b-11e8-9987-4f45bc4f1408.png)

Both systems do have AV - the above is a pretty barebones server, so I'll temporarily remove the AV on mine and re-run... I don't have any proxies installed or anything that I can think of that would interfere with http requests.

**Comment by dougwilson** [comment]
Well, I would suggest the next step is to install Wireshark and get a packet capture of the packets coming from the Node.js server to verify if that is compressed or not. If it is, you have something tampering with your traffic somewhere.

**Comment by dougwilson** [comment]
As for your Edge and Firefox screenshots, it's hard to say, as this module to not compress 304 responses, because a 304 response has no body over the wire to compress.

**Comment by chriseaton** [comment]
You were right - after removing the AV and rebooting, it now shows compressed. 

Interesting side note: both Windows systems had _different_ antivirus's running and both transparently decompressed the http stream. Guess it must be common in the industry. Good to know!

Thanks for your help!

**Comment by dougwilson** [comment]
Ah, glad you found it! I was just about to check out Firefox / Edge on my side to check what they were doing for me. Yea, it's usually when they have a web anti virtual function that they do this -- they don't use a proxy (so you don't see a proxy anywhere): they typically hook directly into the Windows networking stack and so are completely transparent to any tool you'll use (but they cannot scan HTTPS traffic since at that level it's just ciphertext so you won't see the compression lost on HTTPS traffic only HTTP) or they use DLL injection directly into your web browser processes (they can scan HTTPS this way, but it can cause web browser instability).
