### ISSUE TITLE
Not working with static

### ISSUE THREAD

**Issue by rodrigoreis22** [expressjs/compression#35]
I have this simple server:

```js
var express = require('express');
var app = express();
var compression = require('compression');

app.use(express.static(__dirname + '/dist'));
app.use(compression({ threshold: 0 }));

app.all("/*", function(req, res, next) {
  res.sendFile('index.html', { root: __dirname + '/dist' });
});

var server = app.listen(3000, function () {

  var host = server.address().address;
  var port = server.address().port;

  console.log('Example app listening at http://%s:%s', host, port)

});
```

If I set DEBUG=compression and then run `node app.js` , nothing show up.
My response headers doesn't have Content-Encoding: gzip . 

I tried using compression middleware before the static, but got no success as well.

Any ideas?

**Comment by dougwilson** [comment]
Express runs everything in order; you need to `app.use(compression({ threshold: 0 }));` _above_ `app.use(express.static(__dirname + '/dist'));` if you want `express.static` stuff to be compressed.

**Comment by dougwilson** [comment]
```
$ cat example.js
var express = require('express');
var app = express();
var compression = require('compression');

app.use(compression({ threshold: 0 }));
app.use(express.static(__dirname + '/dist'));

app.all("/*", function(req, res, next) {
  res.sendFile('index.html', { root: __dirname + '/dist' });
});

var server = app.listen(3000, function () {

  var host = server.address().address;
  var port = server.address().port;

  console.log('Example app listening at http://%s:%s', host, port)

});
```

```
$ DEBUG=compression node y
Example app listening at http://0.0.0.0:3000
  compression gzip compression +0ms
```

```
$ curl -i -H'Accept-Encoding: gzip' http://127.0.0.1:3000/example.txt
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Date: Wed, 04 Mar 2015 00:59:35 GMT
Cache-Control: public, max-age=0
Last-Modified: Wed, 04 Mar 2015 00:58:42 GMT
ETag: W/"3-395509304"
Content-Type: text/plain; charset=UTF-8
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: keep-alive
Transfer-Encoding: chunked

▼      ♂╦╚T♦ :â╙A♥
```

**Comment by rodrigoreis22** [comment]
Ok, I changed it.

My request:
http://localhost:3000/styles/497f03bf.vendor.css

````
cap-ts-h5-ttys33:express-app rreis3$ DEBUG=compression node app.js
Example app listening at http://0.0.0.0:3000
  compression undefined not compressible +0ms
  compression no compression: filtered +1ms
````

When I try with a txt file, it works:
http://localhost:3000/example.txt

**Comment by dougwilson** [comment]
That message shows that there was no `Content-Type` header in the response, which is why this module wouldn't compress it.

**Comment by dougwilson** [comment]
Simply adding a file `497f03bf.vendor.css` to the `dist/` folder in your example works fine for me with your example code:
```
$ curl -i -H'Accept-Encoding: gzip' http://127.0.0.1:4000/497f03bf.vendor.css
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Date: Wed, 04 Mar 2015 01:12:39 GMT
Cache-Control: public, max-age=0
Last-Modified: Wed, 04 Mar 2015 01:11:15 GMT
ETag: W/"0-1715649385"
Content-Type: text/css; charset=UTF-8
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: keep-alive
Transfer-Encoding: chunked

▼      ♂♥
```

**Comment by dougwilson** [comment]
There is always the possibility you have a corrupted node module somewhere. I would blow everything away and re-installed:
```
$ rm -rf node_modules/
$ npm cache clean
$ npm install
```
and see if that helps.

**Comment by rodrigoreis22** [comment]
Yeah.. It's weird.. I'll investigate more. Thanks,

**Comment by webzepter** [comment]
@rodrigoreis22 @dougwilson I had a similar problem. Thanks for your help! :+1:

**Comment by fkenji** [comment]
Had this happen to me as well with expressjs @4.13.3.  Couldn't pinpoint exactly which express.js version where `res.getHeader('Content-Type')` starts returning `undefined` , as discussed on #37 . It might also be a conflict with other modules, I suppose.

For now the workaround could be implementing a `filter` function that uses ```res.get('Content-Type')``` instead of ```res.getHeader```, based of https://github.com/expressjs/compression/blob/master/index.js#L253 :

```

function shouldCompress(req, res) {
  var type = res.get('Content-Type')

  if (type === undefined || !compressible(type)) {
    debug('%s not compressible', type)
    return false
  }

  return true
}

app.use(compress({ filter: shouldCompress }));

```

**Comment by dougwilson** [comment]
Hi @fkenji , we cannot use that API, as this module works with non-Express based servers. This is a generic middleware that works with the plain Node.js server. Also, I cannot replicate the issue using Express 4.13.3 (and this issue was originally opened before 4.13.3 even existed). So far every time this has happened, it turned out to be your modules/npm cache is just corrupted. Completely `rm -rf node_modules && npm cache clean` and a re-install as resolved.

Rather than resurrecting this old issue, if you are still having this issue even after a complete re-install, please open a new issue with your issue and include the following information:

1. Version of this module
2. Version of Node.js
3. Version of Express
4. Complete app.js code I can copy and paste and run on my machine to reproduce the issue
5. The exact request to make to the app.js call. Ideally just a `cURL` or `wget` command I can just copy-and-paste to the request is identical.
