### ISSUE TITLE
compression does not work with express >= 4.10.0

### ISSUE THREAD

**Issue by FGRibreau** [expressjs/compression#37]
```javascript
var type = res.getHeader('Content-Type')
```

always yield undefined with express >= 4.10.0

- [Express changes](https://github.com/strongloop/express/compare/4.9.8...4.10.0)

**Comment by dougwilson** [comment]
It works just fine. Everything there is a content type issue it's because the install is corrupted on your disk. Please follow the instructions at https://github.com/expressjs/compression/issues/35#issuecomment-77078554 and let me know how it goes.

**Comment by FGRibreau** [comment]
@dougwilson nope, already did it, did not worked, I downgraded express to see where it fails and it fails exactly at 4.10.0

**Comment by dougwilson** [comment]
Ok. I mean, I and thousands of others use it just fine and this middleware doesn't use anything from express. Can you post an example app that doesn't work with the request to make?

**Comment by FGRibreau** [comment]
```javascript
'use strict';

var http = require('http');
var express = require('express');
var path = require('path');
var compression = require('compression');

var app = express();

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// app.use(compression());

app.use('/', (function () {
  // I added this IIFE on purpose to demonstrate you without any JS require
  var express = require('express');
  var router = express.Router();

  /* GET home page. */
  router.get('/', function (req, res, next) {
    res.render('index', {});
  });

  return router;
})());

http.createServer(app).listen(8080);
```

```
└── express@4.12.3
└── compression@1.4.3
```

Request header:

```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
....
```

Response header:

```
Connection:keep-alive
Content-Length:36
Content-Type:text/html; charset=utf-8
Date:Sat, 18 Apr 2015 15:22:04 GMT
ETag:W/"24-ae57b51"
Vary:Accept-Encoding
X-Powered-By:Express
```

**Comment by dougwilson** [comment]
I just pushed up the branch `test-expres-4.12` to this repo which changes every test to use Express 4.12.2 instead of just the plain Node.js HTTP server. Every tests passes with Express 4.12.2: https://travis-ci.org/expressjs/compression/builds/59037148

Feel free to pull down that branch and run it on your machine. If that same branch fails there, you have a corrupted install. If it passes, then it may be some kind of conflict in your existing server code that was brought out with Express.

**Comment by dougwilson** [comment]
@FGRibreau your example it's useful since I cannot run it without the views. Can you simplify it more? Also, I know we posted at the same time, but please also run that scenario above to see what you get.

**Comment by FGRibreau** [comment]
`views/index.jade`:

```
html
  body
    p test
```

I'm sorry I don't have the time to go further (for now)

**Comment by dougwilson** [comment]
@FGRibreau that view's response is not compressed because it's under 1KB in size (see the https://github.com/expressjs/compression#threshold option in the readme). By default we don't compress anything below 1KB, since doing so is useless and sometimes even makes the file bigger instead of smaller.

If you really want that view to be compresses, you can change the `threshold` option.

**Comment by FGRibreau** [comment]
Indeed, I already changed threshold to 0 but at that time it did not worked on my original code, I removed a lot of express middleware since and now it works, thanks

**Comment by dougwilson** [comment]
Ah, I see. It's possible there is a conflict somewhere. Every if it's not a middleware I own, if you find which one is conflicting, please let me know, because I'd like to take a look into it to see if it's something I need to change or the other middleware does.

**Comment by otobrglez** [comment]
Hey guys! I'm using `express@4.13.3` and compressions is still not working. Is there a way to somehow debug compression middleware?
