### ISSUE TITLE
Zlib partial flush

### ISSUE THREAD

**Issue by jakearchibald** [expressjs/compression#41]
I replaced my uses of `res.flush` with `compression({ flush: zlib.Z_PARTIAL_FLUSH })`. Should this be documented as an automatic alternative?

**Comment by dougwilson** [comment]
No, as `Z_PARTIAL_FLUSH` is dangerous and is infact deprecated in zlib. It only exists because some protocols need it (SSH). It also really hurts your compression ratio.

**Comment by dougwilson** [comment]
Though if you can point me to research done on this and what the exact effects are on the underlying byte stream, compression, etc., please let me know and we can reconsider.

**Comment by dougwilson** [comment]
I don't think this flush method is interoperable with all browsers, either (especially older browsers).

**Comment by jakearchibald** [comment]
Looks like it was undeprecated back in 2009 http://www.zlib.net/ChangeLog.txt

I'm using it on https://wiki-offline.jakearchibald.com/wiki/Hulk_Hogan?use-url-flags&avoid-wikipedia=1&prevent-sw=1, and not seeing any change in the gzipped size without it. However, I am no zlib expert.

Kinda worried now, what are the dangers you mentioned?

**Comment by dougwilson** [comment]
So the main thing I saw last time I looked into this was various clients not accepting this kind of flush (the actual streams bytes are different) as well as it doesn't actually flush when you want it to. I see you are trying to flush right after the head and before the body. Using this instead of calling res.flush means it may not flush at the right spot and you won't get exactly what you're looking to get out of this.

If your concern is only modern web browsers and don't care about non web browser clients, then if this flush seems to be working for you, you can certainly use it :)

**Comment by jakearchibald** [comment]
I can't find anything on the browser support, but yeah I'm only targeting modern browsers here.

Yeah, the intention is to flush for the header, but additional flushing is welcome. `res.flush` was working for me, but required a lot of hackery to make it work with dust (a streaming templating language), although I realise that's not this projects problem.

Thanks for the help!
