### ISSUE TITLE
inconsistent use of semicolons

### ISSUE THREAD

**Issue by nickdesaulniers** [expressjs/compression#63]
this makes sending a properly formatted patch hard

**Comment by dougwilson** [comment]
Hi! Sorry, I'm busy today, but just wanted to answer an easy question really quick :) So this project like all other in expressjs/jshttp are expected to conform to no semicolons (https://github.com/jshttp/style-guide). We also have a rule where, to ensure `git blame` and friends works correctly, we don't change the style of the code to conform, only altering the style as the code is actually changed. This means that all lines that still have semicolons just haven't been touched since the new rules went into effect but all others have.

**Comment by nickdesaulniers** [comment]
makes sense
